### ISSUE TITLE
Allow greater control of breakpoints and what is generated per breakpoint

### ISSUE THREAD

**Issue by internetErik** [internetErik/atomic-scss#2]
Add to `_variables.scss`

``` scss
$mobile-first: false !default;

$breakpoints: (
  'lg': '1024px',
  'md': '784px',
  'sm': '560px',
) !default;

// for internal use
$__mqs: ();

// map breakpoints, which are public, to media queries, which are private
@each $bp,$size in $breakpoints {
  $tmp: "all and (max-width: " + $size + ")";
  @if $mobile-first {
    $tmp: "all and (min-width: " + $size + ")";
  }
  $__mqs: map-merge($__mqs, ($bp: $tmp));
}

// border-radius by pixels
$bdrss-px: (
  'default': (1, 2, 3, 4, 5, 6),
  'lg': (1, 2, 3, 4, 5),
  'md': 'default',
  'sm': (1, 2, 3),
) !default;

// border-radius by percentage
$bdrss-perc: (
  'default': (10, 20, 50),
  'lg':  (50),
  'md': 'default',
  'sm': (10),
) !default;

// border-radius by rem
$bdrss-rem: (
  'default': (1,2,3),
) !default;

/*
 All the different types are loaded in. 

To add more, simply define another map of breakpoint names to values
*/
$bdrss: (
  ($bdrss-px  , ''   , 'px' ),
  ($bdrss-perc, '\\%', '%'),
  ($bdrss-rem , 'rem', 'rem'),
) !default;

/*
all the atomic properties packaged together so we can loop on them and generate them all at once
 */
$atomicProperties: (
  $bdrss,
  ...
);
```

Perhaps a new file `_functions.scss`

``` scss
// gets the values that will be used in generating a class for a certain media query
@function __get-mq-vals($map, $key) {
    @if map-get($map, $key) == 'default' {
      @return map-get($map, 'default');
    }
    @else {
      @return map-get($map, $key);
    }
}
```

Re-write of `_borders.scss`

``` scss
// the mixin for border radius
@mixin __bdrs($bdrs, $bp, $post, $unit) {
  $cls: bdrs#{$bdrs}#{$post}\@#{$bp};
  @if $bp == 'default' {
    $cls: bdrs#{$bdrs}#{$post};
  }
  .#{$cls} {
    border-radius: #{$bdrs}#{$unit};
  }
}
```

A file that generates all the styles

``` scss
@each $property in $atomicProperties {
  @each $vals,$post,$unit in $property {
  //eventually @each $vals,$post,$unit,$mixin in $property
    $__vals: map-get($vals, 'default');
    @each $vals in $__vals {
      @include __bdrs($vals, 'default', $post, $unit);
      //eventually @include mixin($mixin, $vals, $bp, $post, $unit);
    }
  }
}

//loop over all properties that we are generating styles for
@each $property in $atomicProperties {

  //loop over all defines breakpoints and their media queries
  @each $bp,$mq in $__mqs {
    //loop over get the values to create, text to put post classname, and a unit for after each value
    @each $vals,$post,$unit in $property {
    //eventually @each $vals,$post,$unit,$mixin in $property
      //if we have a set of values for this breakpoint, write them
      @if map-has-key($vals, $bp) {
        //get the correct values
        $__vals: __get-mq-vals($vals, $bp);
        @media #{$mq} {
          @each $vals in $__vals {
            @include __bdrs($vals, $bp, $post, $unit);
            //eventually @include mixin($mixin, $vals, $bp, $post, $unit);
          }
        }
      }
    }
  }
}
```
